baseURL = 'https://sourabhmisal.github.io/'
languageCode = 'en-us'
title = 'Sourabh Misal'
theme = 'PaperMod'

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

# [[menu.main]]
# identifier = "blog"
# name = "Blog"
# url = "/blog"
# weight = 20

# [[menu.main]]
# identifier = "projects"
# name = "Projects"
# url = "/projects"
# weight = 30

[[menu.main]]
identifier = "experience"
name = "Experience"
url = "/experience"
weight = 40

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search"
weight = 50

[params]
showToc = true
TocOpen = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
hideMeta = false
env = "production"
hideDescriptionInList = false

  [params.profileMode]
  enabled = true
  title = "Sourabh Misal"
  subtitle = "As an Team Coordinator and Embedded Systems Engineer at [**Flux Auto**](https://fluxauto.xyz), I'm not just building embedded systems—I'm engineering the future of automation with [**Drivn**](https://www.drivnhq.com/), our groundbreaking autonomous navigation kit. Picture this: transforming everyday manually driven vehicles into autonomously manuevering sophisticated marvels that navigate warehouses and farms, all while exuding safety, reliablity, scalability and innovation!! Driven by a relentless thirst for mastery in embedded systems, robotics, autonomy, and IoT, I aspire to lead teams in architecting innovative products, seamlessly integrating cutting-edge technologies. Challenges have been invaluable lessons, fueling rapid growth, invaluable learning opportunities and areas for improvement. Each hurdle has swiftly honed my skills, fostering exponential growth and resilience. My goal: Crafting impactful solutions that optimize workflows, improving industries positively and enriching lives."
  imageUrl = "home/sourabh_misal_pic.jpg"
  imageWidth = 220
  imageHeight = 270

  [params.cover]
  hiddenInList = false
  hiddenInSingle = false

  [[params.socialIcons]]
  name = "email"
  url = "mailto:sourabhmisal1@gmail.com"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/sourabhmisal/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/sourabhmisal"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/channel/UCBjy_ciqeNHuvM9K39-LCrg"

  [[params.socialIcons]]
  name = "cv"
  url = "https://drive.google.com/file/d/1E1sWST2BZ_XeMGqNi0wkRDJDXKkLOIDq/view?usp=drive_link"


[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "description", "permalink", "summary", "content" ]

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[markup.goldmark.renderer]
unsafe = true
