baseURL = 'https://sourabhmisal.github.io/'
languageCode = 'en-us'
title = 'Sourabh Misal'
theme = 'PaperMod'

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

# [[menu.main]]
# identifier = "blog"
# name = "Blog"
# url = "/blog"
# weight = 20

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
weight = 40

[[menu.main]]
identifier = "experience"
name = "Experience"
url = "/experience"
weight = 30

# [[menu.main]]
# identifier = "awards"
# name = "Awards"
# url = "/awards"
# weight = 50

# [[menu.main]]
# identifier = "extra"
# name = "Extra-Curriculars"
# url = "/extra-curriculars"
# weight = 50

# [[menu.main]]
# identifier = "blogs"
# name = "Blogs"
# url = "/Blogs"
# weight = 50

[[menu.main]]
identifier = "extra"
name = "Extra-Curriculars"
url = "/extra-curriculars"
weight = 60

# [[menu.main]]
# identifier = "search"
# name = "Search"
# url = "/search"
# weight = 70

[params]
showToc = true
TocOpen = false
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
hideMeta = false
env = "production"
hideDescriptionInList = false

  [params.profileMode]
  enabled = true
  title = "Sourabh Misal"
  subtitle = "I am an Embedded Systems Engineer specializing in Zephyr/FreeRTOS, bootloaders & DFU, and sensor-driven control systems—building across robots, autonomous navigation kits, drones, medical devices, and supply-chain platforms. I’ve delivered production-grade autonomy firmware at Flux Auto; research tooling at NYU ARPL; data-logging stacks at LoadGuard; and a custom Zephyr bootloader plus high-speed nRF52840 drivers at Synaptrix Labs—always optimizing for safety, reliability, and scalability. Recent highlights include a dual-slot Zephyr bootloader with USB DFU and reset-aware handoff; a FreeRTOS multi-sensor pipeline logging RTC-stamped data to microSD for 7+ days; tight vision/IMU sync at 120 Hz using PX4 triggers with ONNX/TensorRT on Jetson; and CANopen-based control for autonomous kits that cut integration time by ~70% and improved responsiveness by ~30%, alongside safety-critical braking/actuation and I²C/SPI/USB driver development across platforms."
  imageUrl = "home/sourabh_misal_pic.jpg"
  imageWidth = 220
  imageHeight = 270

  [params.cover]
  hiddenInList = false
  hiddenInSingle = false

  [[params.socialIcons]]
  name = "email"
  url = "mailto:sourabhmisal1@gmail.com"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/sourabhmisal/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/sourabhmisal"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/channel/UCBjy_ciqeNHuvM9K39-LCrg"

  [[params.socialIcons]]
  name = "cv"
  url = "https://drive.google.com/file/d/1A4ZgwEDydAAqlEyaPOIGNGcRkDkxQ7fx/view?usp=drive_link"


[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "description", "permalink", "summary", "content" ]

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[markup.goldmark.renderer]
unsafe = true
